name: release
on:
  release:
    types:
      - created

jobs:
  release:
    strategy:
      matrix:
        os: 
          - {os: "ubuntu-latest", ext:""}
          - {os: "windows-latest", ext:".exe"}
          - {os: "macos-latest", ext:""}
    name: Build on ${{ matrix.os.os }}
    runs-on: ${{ matrix.os.os.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Depedencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
      - name: Build for ${{ matrix.os.os}}
        run: go build -o /bin/fishsim-${{matrix.os.os}}-${{ github.event.release.tag_name }}${{ matrix.os.ext }}
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin
          asset_name: fishsim-${{ matrix.os.os }}-${{ github.event.release.tag_name }}${{ matrix.os.ext }}
          asset_content_type: binary/octet-stream
